### ISSUE TITLE
Devide Management in C SDK

### ISSUE THREAD

**Issue by rangedsp** [Azure/azure-iot-sdks-preview#11]
Question:
Is device management still supported in C? Having trouble finding documentation / samples. Links that used to work from dmpreview are all broken now, and the MSDN site only has doc for node and C#.

**Comment by pierreca** [comment]
The device management features have been shipped (ie they are not preview anymore). The C SDK does support device management features (on the device side). That is: 
- receiving twin desired properties
- updating twin reported properties
- sending responses to received method calls.

This article gives a good overview of what shipped: 
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-management-overview

The code and samples for each SDK can now be found in each SDK repository: 
- https://github.com/azure/azure-iot-sdk-c
- https://github.com/azure/azure-iot-sdk-node
- https://github.com/azure/azure-iot-sdk-csharp
- https://github.com/azure/azure-iot-sdk-java
- https://github.com/azure/azure-iot-sdk-python

This repository is deprecated for now.

**Comment by rangedsp** [comment]
@pierreca thanks for the information, I am struggling a bit because the documentation for C and the samples seem pretty lacking around device management. 

Are you able to point me to a sample that has C client subscribing to 'desired' property update?

**Comment by ewertons** [comment]
Hi @rangedsp ,
here are a couple examples of how to use device twin (to register for callbacks, etc):
https://github.com/Azure/azure-iot-sdk-c/tree/develop/serializer/samples/devicetwin_simplesample

Another one without using serializer:
https://github.com/Azure/azure-iot-sdk-c/tree/develop/iothub_client/samples/iothub_client_sample_device_method 

And here you can find some articles explaining more about device management:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-management-overview

Please let us know if you need any further help and we will be glad to assist you.

**Comment by rangedsp** [comment]
Thanks a lot @ewertons! 
That sample is exactly what I needed, I kinda figured out how to send reported property by merging iothub_client_sample_mqtt_dm and iothub_client_sample_device_method but was missing the desired send :)
