### ISSUE TITLE
Just some questions

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdks-preview#4]
Hi,

We are looking forward to use device management support from IoT Hub. And we have some questions (feel free to point to doc/page we've not seen yet).

1 - The actual DM implementation does not rely on LWM2M anymore right ?
2 - How can we test DM messages ? When we first look at DM the node.js tool was the only way to deal with DM messages.
3 - From cloud point of view, do we have a defined work flow to make things like firmware update, or it is up the the product team ? It seems that the Pi sample shows a firmware update with only custom properties/commands.

**Comment by olivierbloch** [comment]
Hello @lmussier 
great to hear you are eager to get started on device management features.
To answer your first question, you are correct, the DM implementation doesn't rely any more on LWM2M.
To learn more about how things work now, you can find great documentation on azure.com:
About Device Twins and Methods:
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-device-twins/
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-node-node-twin-getstarted/
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-node-node-twin-how-to-configure/
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-devguide-direct-methods/
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-c2d-methods/
Device Management:
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-device-management-get-started/
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-firmware-update/
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-schedule-jobs/

**Comment by anporumb** [comment]
Closing after more than 5 days with no feedback.

**Comment by lmussier** [comment]
@olivierbloch 
So after some tests and readings here is my understanding.

Since we are no more using LWM2M, the protocol is up to the user. I mean, for the firmware update use case, we have create a service side "function" to send what's look like a complete custom command.
The good thing with LWM2M is we had a semantic to perform some actions (firmware update, reboot, ...), with the current content of this preview we have to create our own protocol to perform generic tasks.

Is this the goal of this new implementation, let users decide what they do, or do you plan to support some device management protocol ?

Ps: @anporumb could you reopen this issue (sounds easier for readers to me)or do you want me to create a new one ?

**Comment by juanjperez** [comment]
Hi @lmussier.  Thanks for the comment and feedback.  

The plan is to provide the abstraction of twin and methods and then build layers on top of that.  This will support a number of protocols, including LWM2M 1.0.  For example, we're working on a LWM2M mapping to Twin/Methods that will enable devices that speak LWM2M 1.0 to a gateway that then does the mapping to Twin and methods.  This provides the extensibility and broad device support that people are asking for while also providing the semantic layering above twin and methods.

I'd love to learn more about your devices.  Do you have devices that implement LWM2M?  Or protocols?

DM me to chat further.

Cheers,
Juan

**Comment by lmussier** [comment]
@juanjperez Sounds interesting, do you have a road map for those functionalities?

For now we have created a set of messages (we use AMQP/WS) to do device management on iothub enabled devices, we also use LWM2M on some other devices (which are not connected to to iothub).
After the first DM preview we thought we'll be able to merge the two streams, iothhub/LWMM2 and our legacy LWM2M, but now the question is do we get rid of our custom messages now, or wait for the SDK to support LWM2M.

My understanding is the SDK won't provide direct LWM2M support, for legacy we'll be able to talk to a gateway which will map LWM2M messages to custom device twin methods. So from a cloud point of view, we won't use any protocol to speak with device, am I right?

If we want an end to end LWM2M messages chain, we have to use a gateway between devices and the hub and some kind of adapter between the hub and our system, is it correct?

Thanks.

Ps: I don't find any direct message route to you Juan.

**Comment by anporumb** [comment]
I hope this answers the original question. If not please feel free to reopen.
