### ISSUE TITLE
DM Device Explorer Unable to retrieve list of devices

### ISSUE THREAD

**Issue by myamama** [Azure/azure-iot-sdks-preview#7]
I wanted to try the new device explorer with DM features. I cloned the repo, built and run the solution as stated in the documentation. Then, I pasted the connection string with "settings updated successfully" popup but then I get an error message whenever I switch to any of the tabs (i.e. Management) I get an error message stating "Unable to retrieve list of devices. Please verify connection strings. {"Message":"Error code invalid: Invalid protocol version: Bad Request}"

**Comment by olivierbloch** [comment]
Hi @myamama
Have you deployed a new IoTHub instance with the Device Management check box checked?

**Comment by myamama** [comment]
Spot on Olivier, I was using an old iot hub that didn't have DM enabled. Now it works with the newly created DM Enabled one. But shouldn't it work even if DM is not enabled? At least the basic functionality?

**Comment by olivierbloch** [comment]
It should and will after we release. For the preview we bumped the API version on the service and have a temporary situation where new tools and SDKs (in the preview repo) don't work with "older" instances of the service.
Closing the issue
