### ISSUE TITLE
HttpRegistryManager Twin Query throws ErrorCode: ArgumentNull and BadRequest

### ISSUE THREAD

**Issue by raven2cz** [Azure/azure-iot-sdks-preview#9]
Hello.
My project with HttpRegistryManager for twin queries (for example SELECT * FROM devices) throws ErrorCode: ArgumentNull and BadRequest. Similar for C# and NodeJS. 
It happens after your new updates to preview.005. 

If I use nuget dll devices lib, it is ok. But there is no visible source codes and the github project doesn't support your new changes!

Can you push new changes which are present in the preview.005? I need to upgrade my code. In actual state, I cannot use IoT Hub!

Thanks for help.

**Comment by pierreca** [comment]
The Node.JS SDK should support that without problem as long as you're using the packages tagged `dtpreview` (which you can install by running `npm install azure-iothub@dtpreview`. can you post the code that's failing and the error that you're seeing, and the version of the package that you are using?

**Comment by raven2cz** [comment]
I have no access to my work today. We have vacation till 11/20/16. So I will post the errors on monday. Thanks for help!

**Comment by raven2cz** [comment]
Focus to C# lang.
There is my simple example which using RegistryManager and CreateQuery method.
It was already work before 3 weeks. But after some update on azure, it doesn't work anymore.

The code is following and using implementation of RegistryManger from:
\git\azure-iot-sdks-preview\csharp\service\Microsoft.Azure.Devices\HttpRegistryManager.cs 

Exception is following:
{"{\"Message\":\"ErrorCode:ArgumentNull;BadRequest\",\"ExceptionMessage\":\"Tracking ID:2c928cface21462c92021285c9329bd0-G:3-TimeStamp:11/21/2016 07:06:53\"}"}
There is nothing more visible in exception.

If I look to the NuGet, there is new library 1.1.0-preview-005 for Microsoft.Azure.Devices which works. But there is no source codes and I don't find it. 
For our project we need source codes because some parts have to implemented in java which is not prepare from your side and it is reason to see your modifications what happen.

**Thanks for help.**

There is example code:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Azure.Devices;
using Microsoft.Azure.Devices.Common.Exceptions;

namespace ConsoleApplication1
{
    class Program
    {
        static RegistryManager registryManager;
        static string connectionString = "<please-your-key-for-test-bug>";

        public static async Task AddTagsAndQuery()
        {
            var query = registryManager.CreateQuery("SELECT * FROM devices", 100);
            while (query.HasMoreResults)
            {
                var page = await query.GetNextAsTwinAsync();
                foreach (var twin in page)
                {
                    Console.WriteLine("Generated device key: {0}", twin.DeviceId);
                }
            }
        }

        static void Main(string[] args)
        {
            registryManager = RegistryManager.CreateFromConnectionString(connectionString);
            AddTagsAndQuery().Wait();
            Console.ReadLine();
        }
    }

}
```

**Comment by raven2cz** [comment]
Hello, any news with our problem. Our development waiting to your ansewers. We cannot solve the problem with seeing how you change api incompatibility.

**Comment by olivierbloch** [comment]
Hi @raven2cz 
we have released new packages and code in our mainstream repo.
The code is here: https://github.com/Azure/azure-iot-sdks
And the latest npm package for the service client (tagged 1.1.0 and no longer in preview) is here: https://www.npmjs.com/package/azure-iothub
Please let us know if that solves your issue

**Comment by raven2cz** [comment]
Thanks for help.
Problem is solved!

The last update of sources in azure/azure-iot-sdks works with actual azure cloud twins queries.
The changes between preview-004 and release are:
- the change of json property "sql" to "query" in the POST of /devices/queries
- change the protocol version 
- the page count is included in the header now, not in the json body content

Done!
